# Generated by Django 5.0.1 on 2024-01-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hackthon_participant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
